# Copyright (c) 2021-2024 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
cases:
  # no 'throws' in foo function
  - defs: |-
      function foo(p: int): void {
          if (p == 1) throw new Exception();
      }
    use: |-
      foo(1);

  - defs: |-
      function foo(p: int): int {
          try {
              return p + 1;
          } catch (e) {
              if (p == 1) throw new Exception();
          }
      }
    use: |-
      foo(1);

  - defs: |-
      function foo(p: int): int {
          try {
              return p + 1;
          } catch (e) {
              return -1;
          } finally {
              if (p == 1) throw new Exception();
          }
      }
    use: |-
      foo(1);

  # no 'throws' in main function
  - defs: |-
      function foo(p: int): void throws {
          if (p == 1) throw new Exception();
      }
    use: |-
      foo(1);

  - defs: |-
      function foo(p: int): int throws {
          try {
              return p + 1;
          } catch (e) {
              return -1;
          } finally {
              if (p == 1) throw new Exception();
          }
      }
    use: |-
      foo(1);

  # not an exception class in throw
  - defs: |-
      class A {}
    use: |-
      let p: A = new A();
      try {
          throw p;
      } catch (e) {
          // ignore
      }

  - use: |-
      try {
          throw new Object();
      } catch (e) {
          // ignore
      }
